{
 "title": "Plex",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Active Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "plex_active_sessions_count{job=\"plex_exporter\"}",
     "legendFormat": "sessions"
    }
   ]
  },
  {
   "title": "Active Sessions by user and device",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (device) (plex_active_sessions_count_user_device)",
     "legendFormat": "Device - {{device}}"
    },
    {
     "expr": "sum by (user) (plex_active_sessions_count_user_device)",
     "legendFormat": "User - {{user}}"
    }
   ]
  },
  {
   "title": "Instant Active Sessions",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "plex_active_sessions_count{job=\"plex_exporter\"}"
    }
   ]
  },
  {
   "title": "Medias by Type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 7, "x": 5, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (type) (plex_library_count)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Medias",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 8, "x": 12, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "plex_library_count  ", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Total Medias",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(plex_library_count)" }
   ]
  }
 ]
}