name: Golang CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  golangci-lint:
      name: lint
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: golangci-lint
          uses: golangci/golangci-lint-action@v2
          with:
            version: v1.33.0
            # Optional: show only new issues if it's a pull request. The default value is `false`.
            only-new-issues: true
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go_version: [1.16]
    steps:
      - name: checkout  
        uses: actions/checkout@v2
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }} 
      - name: go tests
        run: |
          echo "getting dependencies...".
          go get -v -u ./...
          echo "go test for ${{ matrix.os }} and version ${{ matrix.go_version }}".
          go test -v ./... -cover -race
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: plex_exporter-${{ matrix.os }}
          path: ${{ github.workspace }}/dist/**/*
          retention-days: 10          